# Default configuration. Copy this file to config.ini and edit it to your needs.

[SENSOR]
# Alignment of the compass vs the zero point for the wind direction
# Point the compass straight into the wind and read the compass heading and wind angle
# Subtract the read wind angle from the heading to receive the COMPASS_OFFSET
# Positive values indicate that the north of the measurement unit is offset clockwise from the compass north.
COMPASS_OFFSET_DEGREES = 0

[LOGGING]
# Name of the log file. If empty, will only log to the console
LOG_FILE = master.log
# Which information should be logged, default is WARNING
# Possible values: DEBUG, INFO, WARNING, ERROR
LOG_LEVEL = WARNING
# Maximum size of the log file in kilobytes. If the file exceeds this size, it will be rotated
# Default is 5000 KB (5 MB)
MAX_LOG_SIZE = 5000
# Maximum number of log files to keep. If the number of log files exceeds this value, the oldest file will be deleted
# Default is 10
MAX_LOG_FILES = 10

# Name of the directory for data log files. If empty, will not log data streams
DATA_LOG_DIR = data_logs
# Maximum size of each data log file in kilobytes. If the file exceeds this size, it will be rotated
# Default is 100'000 KB (100 MB)
MAX_DATA_LOG_SIZE = 100000

[NETWORK]
# Order in which order the network interfaces should be used if available.
# If empty, the default interface will be used.
INTERFACE_PRIORITY = wlan0, usb0

# Start a local webserver to display the data
# If enabled and not connected to a network, an access point will be created
ENABLE_LOCAL_WEBSERVER = false

# SSID and password for the access point
AP_SSID = WindSensor
AP_PASSWORD = WindSensor


[MQTT]
# Address of the MQTT broker, if commented out, MQTT will be disabled
BROKER = broker.hivemq.com
PORT = 8883

# Credentials for the MQTT broker. Uncomment if needed
#USERNAME =
#PASSWORD =

CLIENT_ID = bot1
TOPIC = bot1

# How many datapoints should be grouped together before sending them to the MQTT broker
# This allows for data savings at the cost of increased latency. To effectively disable, set to 1
# Maximum is 30
QUEUE_SIZE = 5
